### ISSUE TITLE
Empty response body in non 204 status code

### ISSUE THREAD

**Issue by shuhei** [zalando-incubator/perron#12]
Currently [response `content-type` is implicitly decided by status code 204 or not](https://github.com/zalando-incubator/perron/blob/master/lib/client.js#L77). However, there are other status codes like 3xx and 404 with which empty body seems to be valid. Because [response without body doesn't need to specify `content-type`](http://stackoverflow.com/questions/29784398/should-content-type-header-be-present-when-the-message-body-is-empty), there is no sane way to prevent `perron` from trying to parse empty body as JSON without setting arbitrary `content-type` on the server side.

**Comment by grassator** [comment]
@shuhei I think the behavior of perron is correct in this case. It is certainly possible to have a 404 or 3xx response without a body, but it's *not* a valid JSON, so it should be treated as such.

204 status code (according to [RFC](https://tools.ietf.org/html/rfc7231#section-6.3.5)) on other hand *requires* that there is no body, in which case it can never be a valid json:

>   A 204 response is terminated by the first empty line after the header fields because it **cannot** contain a message body.

I understand that there might be clients that are not compliant to spec so perron should have a strategy for dealing with those. I think a better way to do this is to move out this functionality out of the core and into a filter that is enabled by default. This is a breaking change, but I feel that it's a good one to make.

**Comment by shuhei** [comment]
I agree that the behavior is correct in the 204 case. But my current problem is that I'm getting errors with 3xx and 4xx responses without a body or `content-type` and I can't find a way to avoid it.

I agree that JSON parsing as a default filter will give users more flexibility, but yet I think that the default filter should not fail on non-204 response without a body or `content-type`.

I believe that #13 fixes the problem without any breaking changes. I don't think anyone is relying JSON parsing error for an empty body. What do you think?
