### ISSUE TITLE
Add retrying with exponential backoff 

### ISSUE THREAD

**Issue by grassator** [zalando-incubator/perron#18]
To help deal with intermittent network failures, the library should implement exponential backoff retrying.

[backoff library](https://www.npmjs.com/package/backoff) on NPM is probably worth a look.

### More Info
https://cloud.google.com/storage/docs/exponential-backoff
https://www.awsarchitectureblog.com/2015/03/backoff.

**Comment by Joneser** [comment]
@grassator I'll look into implementing this week
