### ISSUE TITLE
timeout option is not working

### ISSUE THREAD

**Issue by shuhei** [zalando-incubator/perron#19]
The `timeout` option does not make slow responses errors. It's because the `timeout` option of `http.request()` only emits `timeout` event when it timeouts instead of severing the request.

Because `perron` is not exposing the request object returned by `http.request()`, users cannot listen to the `timeout` event and abort the request.

**Comment by grassator** [comment]
@shuhei What would you see as the fix for this problem, can you submit a PR?

**Comment by shuhei** [comment]
I think we have two ways:

1. If we stick with the same options as `https.request()`, we can listen to the `timeout` event and abort the request. But this timeout is [a timeout for inactive socket](https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback) and it allows requests to take more than `timeout`. The timeout timer is reset in `lookup` event, `connect` event, and each data read and write on the socket. If you have 200 ms timeout and it takes 50 ms for lookup, 50 ms for socket connect, 150 ms for the response headers, the `timeout` event is not emitted.
2. Another solution would be measuring time to the last byte by our own and rejecting the result promise with an error. I think this is useful and what most of the users expect.

What do you think?

**Comment by shuhei** [comment]
`request` and `axios` have `timeout` for the time before response headers. But it makes sense for `perron` to have a `timeout` for the time before the last byte because `perron` always wait for response body to resolve the result promise.

**Comment by grassator** [comment]
@shuhei what is the reason to trigger timeout after the last byte is received? I mean we have already got all the data anyway, unless I misunderstand something...

Why can't we just listen to `timeout` event and then call `end()` on the socket and report the request as failure?

**Comment by shuhei** [comment]
I am not sure about your question, but there is no reason to trigger timeout after the last byte is received.

It looks great to have the 2 options. I'll create a pull request.

**Comment by grassator** [comment]
@shuhei sorry I now realize I misunderstood your explanation about axios and request.

Looking forward to the PR
