### ISSUE TITLE
Add debugging information to request errors

### ISSUE THREAD

**Issue by shuhei** [zalando-incubator/perron#24]
Currently errors from `request.js` don't have information about the requests and it's hard to know what's going by only looking at the error messages. Request host, path, etc. should be useful for debugging.

https://github.com/zalando-incubator/perron/pull/23#discussion_r118657578

**Comment by julianusti** [comment]
@shuhei @grassator 
Does anyone work on this issue? If not, I'd like to contribute.

**Comment by grassator** [comment]
@julianusti not that I'm aware of, so contributions are welcome.
