### ISSUE TITLE
Ability to specify a name for service clients

### ISSUE THREAD

**Issue by mo-gr** [zalando-incubator/perron#35]
I would like to have the (optional) ability to specify a name for a service client.

Named service clients should use that name in all generated errors. We currently have a project with about a dozen service clients and it is sometimes not straight-forward to correlate errors in our logs with the causing client.

**Comment by grassator** [comment]
Wouldn't it be enough to use hostname for this purpose?

**Comment by mo-gr** [comment]
For our use cases: yes. But I could imagine a scenario, where people have multiple clients to the same hostname and would still like to differentiate them in their error messages.
