### ISSUE TITLE
req object is undefined

### ISSUE THREAD

**Issue by jans510** [zalando-incubator/perron#39]
On using the retry logic as defined in the readme with the function
`onRetry(currentAttempt, err, req) {
            console.log('Retry attempt #' + currentAttempt + ' for ' + req.path + ' due to ' + err);
        }`
to log the retries, no log entries are written as the req object is undefined, which leads to an exception.

It would be nice if this function gets rewritten or the request gets pasted into the req property.

**Comment by shuhei** [comment]
Which version of perron are you using?

**Comment by jans510** [comment]
sorry, I used the wrong version, I'll close the issue
