### ISSUE TITLE
Parse response body of `application/foo+json`

### ISSUE THREAD

**Issue by shuhei** [zalando-incubator/perron#40]
Some API servers use [Structured Syntax Suffixes](https://tools.ietf.org/html/rfc6838#section-4.2.8) like `application/foo+json` for `Content-Type`, `Accept`, etc.

Currently perron parses response body as JSON only when `Content-Type` starts with `application/json`. Does it make sense to parse body as JSON also when `Content-Type` is suffixed by `+json`?

**Comment by grassator** [comment]
@shuhei I think it totally makes sense
