### ISSUE TITLE
Incoherent behaviour of ServiceClient based on given options

### ISSUE THREAD

**Issue by bzums** [zalando-incubator/perron#64]
Hey all!

```ts
const client = new ServiceClient('http://0.0.0.0');
client.request({ pathname: '/' })
```

will perform a request to `http://0.0.0.0` whereas:

```ts
const client = new ServiceClient({ hostname: 'http://0.0.0.0' });
client.request({ pathname: '/' })
```

will perform a request to `http://0.0.0.0:443`.

If I have already defined a port explicitly in `hostname`, `:443` is appended nevertheless.

That behaviour seems quite confusing to me.

**Comment by shuhei** [comment]
Hi, thanks for your feedback.

This happens because `hostname`, which is from Node.js `http.request()` options, shouldn't have protocol or port in it. The argument of the first example is for convenience and not `hostname`.

Probably we should have a better documentation.
