### ISSUE TITLE
Bug: extra `?` added to end of urls

### ISSUE THREAD

**Issue by mroderick** [zalando-incubator/perron#69]
When the `query` option is not defined, the url will have a `?` at the end.

For some cases, that is fine, but when you pass a `pathname` option that contains a query string, the result is the request being made to an invalid url.

```js
const client = new ServiceClient("https://some.host");
client.request({
    pathname: "/some/path/with?query=string"
});
```

This will result in requests being made to `https://some.host/some/path/with?query=string?`, which is an invalid url. The invalid url will not be parsed properly by some url parsers ... I discovered this bug by making requests using invalid urls for a Ruby on Rails server, which definitely did not understand how to parse my requests 😉 

The solution in my case was to use the `query` option.

However, I do think that Perron should do something about this mistake, which is easily detectable.

My preferred solution would be for an error to be thrown.

**Comment by grassator** [comment]
What you are encountered is indeed a combination of a small bug and an non obvious choice around handling paths. I've created a PR to remove question mark for the cases of empty query, however `pathname` is a wrong option to use with a query. You should either use `pathname` + optionally `query`, or if your path already contains query you should use `path` instead.

**Comment by grassator** [comment]
New version 0.7.1 published

**Comment by mroderick** [comment]
> What you are encountered is indeed a combination of a small bug and an non obvious choice around handling paths. I've created a PR to remove question mark for the cases of empty query.

Thank you 👍 



> however `pathname` is a wrong option to use with a query. You should either use `pathname` + optionally `query`, or if your path already contains query you should use `path` instead.

I realised that, and fixed it :)
